# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://YichengShen.github.io/car_speech/"

git_url = "https://github.com/YichengShen/car_speech/tree/master/"

def custom_doc_links(name): return None
