# AUTOGENERATED! DO NOT EDIT! File to edit: 00_Download_Data.ipynb (unless otherwise specified).

__all__ = ['download_data']

# Cell
import pathlib
import tensorflow as tf

# Cell
def download_data(dataset_type):
    data_dir = pathlib.Path('data/avicar_some'+dataset_type)

    file_name = 'avicar_some' + dataset_type + '.zip'
    download_link = "http://www.isle.illinois.edu/speech_web_lg/data/avicar_some" + dataset_type + ".zip"

    if not data_dir.exists():
        tf.keras.utils.get_file(
            file_name,
            origin=download_link,
            extract=True,
            cache_dir='.', cache_subdir='data')
        print("download completed")
    else:
        print("data_dir already exists")